### ISSUE TITLE
提一个小bug，类型string []的备注没有添加上。

### ISSUE THREAD

**Issue by Link-X** [Nuibia/chrome-yapi2ts#1]
![image](https://github.com/Nuibia/chrome-yapi2ts/assets/31473212/4fff9f6a-2cd1-481a-8fec-72a027f6763b)

![image](https://github.com/Nuibia/chrome-yapi2ts/assets/31473212/e790efbb-fbab-4636-b9c1-325fe0a18397)

如图。

**Comment by Nuibia** [comment]
我找时间看下，感谢使用

**Comment by Nuibia** [comment]
已修复
